language: python
matrix:
  include:
  - name: "Attiny85"
    python: "2.7"
    env: 
      - PLATFORMIO_CI_SRC=./Attiny85
      - CFG_PATH=./Attiny85
  - name: "Attiny85 LOG_ON"
    python: "2.7"
    env: 
      - PLATFORMIO_CI_SRC=./Attiny85
      - CFG_PATH=./Attiny85
      - LOG_ON=1
  - name: "ESP8266 (CLASSIC & 4C2W)"
    python: "2.7"
    env: 
      - PLATFORMIO_CI_SRC=./ESP8266 
      - CFG_PATH=./ESP8266
git:
  depth: 3
  submodules: false

branches:
  only:
  - master
  
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio

script:
    - platformio ci --project-conf=$CFG_PATH/platformio.ini
    
notifications:
  email:
    on_success: change
    on_failure: change